//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]
[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.71")]

namespace BookRaiders.Earlybound
{
    /// <summary>
    /// Represents a source of entities bound to a CRM service. It tracks and manages changes made to the retrieved entities.
    /// </summary>
    public partial class CrmServiceContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
    {
        
        /// <summary>
        /// Constructor.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode()]
        public CrmServiceContext(Microsoft.Xrm.Sdk.IOrganizationService service) :
                base(service)
        {
        }

        /*
        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.Account"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.Account> AccountSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.Account>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.ActivityPointer"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.ActivityPointer> ActivityPointerSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.ActivityPointer>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.Appointment"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.Appointment> AppointmentSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.Appointment>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.BusinessUnit"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.BusinessUnit> BusinessUnitSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.BusinessUnit>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.Contact"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.Contact> ContactSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.Contact>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.Email"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.Email> EmailSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.Email>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.EntityDataProvider"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.EntityDataProvider> EntityDataProviderSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.EntityDataProvider>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.EntityDataSource"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.EntityDataSource> EntityDataSourceSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.EntityDataSource>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.LanguageLocale"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.LanguageLocale> LanguageLocaleSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.LanguageLocale>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.mcsbr_interacao"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.mcsbr_interacao> mcsbr_interacaoSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.mcsbr_interacao>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.Organization"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.Organization> OrganizationSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.Organization>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.PhoneCall"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.PhoneCall> PhoneCallSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.PhoneCall>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.Role"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.Role> RoleSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.Role>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.smt_az_sql_product_model"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.smt_az_sql_product_model> smt_az_sql_product_modelSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.smt_az_sql_product_model>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.smt_azure_sql_data_source"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.smt_azure_sql_data_source> smt_azure_sql_data_sourceSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.smt_azure_sql_data_source>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.smt_bpf_contact_ignore"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.smt_bpf_contact_ignore> smt_bpf_contact_ignoreSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.smt_bpf_contact_ignore>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.smt_contact_smt_az_sql_product_model"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.smt_contact_smt_az_sql_product_model> smt_contact_smt_az_sql_product_modelSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.smt_contact_smt_az_sql_product_model>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.smt_customer_portfolio"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.smt_customer_portfolio> smt_customer_portfolioSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.smt_customer_portfolio>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.smt_portfolio_configuration"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.smt_portfolio_configuration> smt_portfolio_configurationSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.smt_portfolio_configuration>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.SystemUser"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.SystemUser> SystemUserSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.SystemUser>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.SystemUserRoles"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.SystemUserRoles> SystemUserRolesSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.SystemUserRoles>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.Task"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.Task> TaskSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.Task>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.Team"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.Team> TeamSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.Team>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.TeamMembership"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.TeamMembership> TeamMembershipSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.TeamMembership>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.TeamRoles"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.TeamRoles> TeamRolesSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.TeamRoles>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.UserSettings"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.UserSettings> UserSettingsSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.UserSettings>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="BookRaiders.Earlybound.WebResource"/> entities.
        /// </summary>
        public System.Linq.IQueryable<BookRaiders.Earlybound.WebResource> WebResourceSet
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.CreateQuery<BookRaiders.Earlybound.WebResource>();
            }
        }
        */
    }
    
    internal sealed class EntityOptionSetEnum
    {

        [System.Diagnostics.DebuggerNonUserCode()]
        public static System.Nullable<int> GetEnum(Microsoft.Xrm.Sdk.Entity entity, string attributeLogicalName)
        {
            if (entity.Attributes.ContainsKey(attributeLogicalName))
            {
                Microsoft.Xrm.Sdk.OptionSetValue value = entity.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>(attributeLogicalName);
                if (value != null)
                {
                    return value.Value;
                }
            }
            return null;
        }

        [System.Diagnostics.DebuggerNonUserCode()]
        public static System.Collections.Generic.IEnumerable<T> GetMultiEnum<T>(Microsoft.Xrm.Sdk.Entity entity, string attributeLogicalName)

        {
            Microsoft.Xrm.Sdk.OptionSetValueCollection value = entity.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValueCollection>(attributeLogicalName);
            System.Collections.Generic.List<T> list = new System.Collections.Generic.List<T>();
            if (value == null)
            {
                return list;
            }
            list.AddRange(System.Linq.Enumerable.Select(value, v => (T)(object)v.Value));
            return list;
        }

        [System.Diagnostics.DebuggerNonUserCode()]
        public static Microsoft.Xrm.Sdk.OptionSetValueCollection GetMultiEnum<T>(Microsoft.Xrm.Sdk.Entity entity, string attributeLogicalName, System.Collections.Generic.IEnumerable<T> values)

        {
            Microsoft.Xrm.Sdk.OptionSetValueCollection collection = new Microsoft.Xrm.Sdk.OptionSetValueCollection();
            collection.AddRange(System.Linq.Enumerable.Select(values, v => new Microsoft.Xrm.Sdk.OptionSetValue((int)(object)v)));
            return collection;
        }
    }

    /// <summary>
    /// Attribute to handle storing the OptionSet's Metadata.
    /// </summary>
    [System.AttributeUsageAttribute(System.AttributeTargets.Field)]
    public sealed class OptionSetMetadataAttribute : System.Attribute
    {

        /// <summary>
        /// Color of the OptionSetValue.
        /// </summary>
        public string Color { get; set; }

        /// <summary>
        /// Description of the OptionSetValue.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Display order index of the OptionSetValue.
        /// </summary>
        public int DisplayIndex { get; set; }

        /// <summary>
        /// External value of the OptionSetValue.
        /// </summary>
        public string ExternalValue { get; set; }

        /// <summary>
        /// Name of the OptionSetValue.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="OptionSetMetadataAttribute"/> class.
        /// </summary>
        /// <param name="name">Name of the value.</param>
        /// <param name="displayIndex">Display order index of the value.</param>
        /// <param name="color">Color of the value.</param>
        /// <param name="description">Description of the value.</param>
        /// <param name="externalValue">External value of the value.</param>
        [System.Diagnostics.DebuggerNonUserCode()]
        public OptionSetMetadataAttribute(string name, int displayIndex, string color = null, string description = null, string externalValue = null)
        {
            this.Color = color;
            this.Description = description;
            this.ExternalValue = externalValue;
            this.DisplayIndex = displayIndex;
            this.Name = name;
        }
    }

    /// <summary>
    /// Extension class to handle retrieving of OptionSetMetadataAttribute.
    /// </summary>
    public static class OptionSetExtension
    {

        /// <summary>
        /// Returns the OptionSetMetadataAttribute for the given enum value
        /// </summary>
        /// <typeparam name="T">OptionSet Enum Type</typeparam>
        /// <param name="value">Enum Value with OptionSetMetadataAttribute</param>
        [System.Diagnostics.DebuggerNonUserCode()]
        public static OptionSetMetadataAttribute GetMetadata<T>(this T value)
            where T : struct, System.IConvertible
        {
            System.Type enumType = typeof(T);
            if (!enumType.IsEnum)
            {
                throw new System.ArgumentException("T must be an enum!");
            }
            System.Reflection.MemberInfo[] members = enumType.GetMember(value.ToString());
            for (int i = 0; (i < members.Length); i++
            )
            {
                System.Attribute attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(members[i], typeof(OptionSetMetadataAttribute));
                if (attribute != null)
                {
                    return ((OptionSetMetadataAttribute)(attribute));
                }
            }
            throw new System.ArgumentException("T must be an enum adorned with an OptionSetMetadataAttribute!");
        }
    }
}